[project]
name = "the-codemaster"
version = "0.0.14"
description = "the-codemaster"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame-ce>=2.5.3",
    "pygame-gui>=0.6.13",
]
