"""Package levels."""
from codemaster.levels.level_base import Level
from codemaster.levels.level_01 import Level1
from codemaster.levels.level_02 import Level2
from codemaster.levels.level_03 import Level3
from codemaster.levels.level_04 import Level4
from codemaster.levels.level_05 import Level5
from codemaster.levels.level_06 import Level6
from codemaster.levels.level_07 import Level7
from codemaster.levels.level_08 import Level8
from codemaster.levels.level_09 import Level9
from codemaster.levels.level_10 import Level10
from codemaster.levels.level_11 import Level11
from codemaster.levels.level_12 import Level12
from codemaster.levels.level_13 import Level13
from codemaster.levels.level_14 import Level14
from codemaster.levels.level_15 import Level15
from codemaster.levels.level_16 import Level16
from codemaster.levels.level_17 import Level17
from codemaster.levels.level_18 import Level18
